### ISSUE TITLE
Report Date Format

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-viz-prototype#107]
The Report Date format at the bottom of the page for tables 3-1 and 3-2 are in Non American format.
Currently is: dd/mm/yyyy
Should be: mm/dd/yyyy

![image](https://cloud.githubusercontent.com/assets/9752096/6717221/76a1051c-cd81-11e4-9373-8abf90dc1721.png)

**Comment by Kibrael** [comment]
I fixed this in the processing code.
