### ISSUE TITLE
CSV button in Internet Explorer does not work

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-viz-prototype#108]
Nothing happens when I click on the csv button in IE:

![image](https://cloud.githubusercontent.com/assets/9752096/6803396/98ae8b94-d20d-11e4-81f8-20523e8470b7.png)

**Comment by lesgou** [comment]
Also, when I export in Chrome on my other laptop, it opens in google sheet, instead of microsoft excel.

**Comment by awolfe76** [comment]
IE 9 has a workaround but users would have to copy/paste (or file > save as) to get the csv content and then paste into Excel.

Other option is only supporting IE 10+. Wanted to see what you thought first @lesgou @Kibrael .

Some references:
http://www.zachhunter.com/2010/11/download-json-to-csv-using-javascript/
http://hackworthy.blogspot.com/2012/05/savedownload-data-generated-in.html
