### ISSUE TITLE
Verifying data in table 3-2

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-viz-prototype#113]
The red highlighted cells are from HMDA Viz prototype.  The blue highlighted cells are from the FFIEC website.  

I pulled 2013/Alabama/Anniston-Oxford.  Most of the numbers match.  The main difference is with "other purchaser"

![image](https://cloud.githubusercontent.com/assets/9752096/6847044/d8440814-d399-11e4-9ed4-70fed3e77fde.png)

![image](https://cloud.githubusercontent.com/assets/9752096/6847050/e7cc05f2-d399-11e4-9df6-1f6051f624cf.png)

**Comment by Kibrael** [comment]
This looks like it was fixed when i rewrote the SQL statements. 

I'll wait to close it until we see it served on the front end.

**Comment by lesgou** [comment]
Looks good.  The differences may just be rounding.  Please see yellow highlighted cells:

![image](https://cloud.githubusercontent.com/assets/9752096/6952292/e30ba2da-d88e-11e4-9fb0-5759ab66a424.png)

![image](https://cloud.githubusercontent.com/assets/9752096/6952301/f69cd6d4-d88e-11e4-8285-0ac4301eee08.png)

![image](https://cloud.githubusercontent.com/assets/9752096/6952310/0498bba4-d88f-11e4-88fd-7d2be55ba484.png)

![image](https://cloud.githubusercontent.com/assets/9752096/6952325/2549ca78-d88f-11e4-8fab-b5f86ec69563.png)

**Comment by Kibrael** [comment]
The largest differences seem to be in the weighted median. If possible, it'd be helpful to have the formula the FFIEC uses. I can spend some more time looking into this, but I don't think it's a priority.

**Comment by Kibrael** [comment]
Leslie and I believe we have found the calculation.

Step 1) if rate spreads are the same, collapse the rows by adding the loan amounts together
Step 2) find the sum of the loan amounts
Step 3) divide the sum of loan amounts by the new number of rows (average loan amount)
Step 4) divide each row's loan amount by the average loan amount (how many 'steps' the row counts for)
Step 5) at each row, show the cumulative 'steps'
Step 6) when a row's cumulative 'step' count equals or exceeds the 50th percentile of the rows by count (eg 11 rows would be 6) take the rate spread in that row as the weighted median.

I will implement this in code next week.
