### ISSUE TITLE
Update to Category in Table 4's

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-viz-prototype#123]
I think there is an extra space in "Asian"

![image](https://cloud.githubusercontent.com/assets/9752096/6925757/a975afb4-d7af-11e4-91ab-e5a8742a1daf.png)

**Comment by awolfe76** [comment]
Was this fixed?
I don't see a space like that:
![spacing](https://cloud.githubusercontent.com/assets/2932572/6925820/260772e2-d7b0-11e4-8467-215d6e564382.png)

**Comment by lesgou** [comment]
and maybe one for alaska?

![image](https://cloud.githubusercontent.com/assets/9752096/6925893/b58a1d3e-d7b0-11e4-80c0-2ccb2429e6b1.png)

**Comment by lesgou** [comment]
Based on the developer tools in Chrome, it looks like there is no space after all.
