### ISSUE TITLE
Verifying data in table 3-1

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-viz-prototype#130]
Please see the non highlighted cells in the Mantis columns:

![image](https://cloud.githubusercontent.com/assets/9752096/6929129/742f62a2-d7c6-11e4-842d-72e8c1266134.png)

**Comment by Kibrael** [comment]
The minority percent section is mostly fixed. There was a missing index line. Freddie Mac doesn't match for the <10% minority line. I was able to find the LAR entry and it has NA listed for minority population precent. Do we know if NA defaults to <10%?

**Comment by Kibrael** [comment]
The ethnicity error occurred because I was including co-applicant information to set the loan's ethnicity. When I do not consider co-applicant ethnicity, the count and values match the FFIEC.

**Comment by Kibrael** [comment]
I will go through and make changes to remove co-applicant from calculations.
