### ISSUE TITLE
Opening json in IE

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-viz-prototype#147]
Currently, when I click on the "json" button, it opens this page in chrome:

![image](https://cloud.githubusercontent.com/assets/9752096/7091432/9738ac5a-df77-11e4-89b7-cf1e432f7c67.png)

When I click on the button in IE 9 and IE 10, I am given this option:

![image](https://cloud.githubusercontent.com/assets/9752096/7091455/bd1914aa-df77-11e4-89c3-e1b783a9bccd.png)

Should that be happening in IE?

**Comment by awolfe76** [comment]
We'll probably remove that button. From the UI it's not the useful.
