### ISSUE TITLE
Table 5's Number

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-viz-prototype#153]
I think the the numbers are off by one row?  For tables 5-1 to 5-7

![image](https://cloud.githubusercontent.com/assets/9752096/7123496/6a68473c-e1f0-11e4-8354-a25d73d1c5bd.png)

**Comment by Kibrael** [comment]
All the aggregation lines were accessing the same part of the JSON structure. 

The error was that the OrderedDicts were not re-initiated before being appended to different parts of the JSON structure. Apparently this links them when the values in the object are changed.
