### ISSUE TITLE
report_list.json files

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-viz-prototype#158]
We're creating MSA-MD folders when no reports exist. The folder has the report_list.json file with just an empty object.
Here is an example:
https://github.com/cfpb/hmda-viz-prototype/tree/gh-pages/aggregate/2013/alabama/albertville
- [ ] don't create the msa-md folder if there are no reports
- [ ] rename the file to either reports.json or report-list.json (with a hyphen) to be consistent with other file/folder names

**Comment by Kibrael** [comment]
I changed the reports_list.json to reports-list.json.

The other part is more complex. I'll think about how to do it and get back to you.
