### ISSUE TITLE
Need a state and MSA list

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-viz-prototype#31]
Would like to get a state list, including id, full name, and 2 char abbr.
Same for MSA/MD's, including id, name, and state (2 char abbr at least).

We can then decide if we need to break down the MSA's in anyway, for sure by state, based on the need of the processing and front-end.

Oh, need these lists in a machine readable format. :smile:

**Comment by lesgou** [comment]
I faxed all this information to you.  Now we just need to create a system that will turn that into machine readable format.  :+1: 

This will be done today.

**Comment by lesgou** [comment]
Posted on google docs:

1) List of all states, DC, and PR (FIPS code, state code, state name)
https://drive.google.com/open?id=0B667BGHwjTznSDJYelpBd1UwV2s&authuser=0

2) List of All MSA/MD name, Tract, county, MSA, MD, Small County flag, County, State FIPS Code, State Code

https://drive.google.com/open?id=0B667BGHwjTznRVk1bkNJaWs4RlE&authuser=0
