### ISSUE TITLE
Aggregation by Race

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-viz-prototype#37]
Current state: aggregation is done by FFIEC footnotes, typically using just 1 minority race from each applicant.

Potential states:
     1) atomize by combinations of races
     2) add loan to each race category it could belong to
     3) other?

**Comment by Kibrael** [comment]
This should be moved out of the milestone.

**Comment by awolfe76** [comment]
Done!

**Comment by Kibrael** [comment]
We addressed this with Regs and decided to use co-applicant if applicant race was unavailable. For the rest, I think this is for future state work.
