### ISSUE TITLE
Which state name?

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-viz-prototype#43]
How will we determine which state name to use in cases where the MSA spans multiple states?

If this is determined by user selection path of the report (user chooses state then MSA), do we need to have multiple JSON files stored, or do we need a dynamic header selection?

**Comment by awolfe76** [comment]
An example is 'MSA/MD: 17980 - COLUMBUS, GA-AL'.

When you start the process to get there you can select Alabama and see that MSA listed.
Also if you select Georgia, you see that MSA listed.

In both PDFs (in the header) it says 'MSA/MD: 17980 - COLUMBUS, GA-AL'.

Given the current setup on the front-end, the `.json` files live in the directories, I think we need 2 copies of the same json file created. In this example one would live in `/aggregate/2013/alabama/columbus/[table#]` and the other in `/aggregate/georgia/columbus/[table#]`.

Make sense?

**Comment by Kibrael** [comment]
Sounds good, thanks for getting back to me on that.

I'll work on a concatenation piece for the header.
