### ISSUE TITLE
Add MSA friendly name to json

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-viz-prototype#44]
We need to add the friendly name to the json objects.

For example:

```
"msa-md": {
    "id": "11500",
    "name": "Anniston-Oxford",
    "state": "AL"
}
```

The "name" key.

**Comment by Kibrael** [comment]
In this case is it better to modify the table in the database or to join with another table? Or does it not matter?

**Comment by awolfe76** [comment]
Either will work. A new table with that data or just adding a column.
Whatever is going to be easier for you right now, I suspect just adding the new column.

Up to you though.
