### ISSUE TITLE
Displaying all columns and rows in the "print" version of the tables

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-viz-prototype#48]
When users print the table, all columns and rows should be printed (not cut off).

**Comment by awolfe76** [comment]
@lesgou can you give me a screen shot or something for an example? When I print it's ok.
![viz-print](https://cloud.githubusercontent.com/assets/2932572/6134198/95428a7e-b12d-11e4-94b0-177a4b0f77df.png)

**Comment by lesgou** [comment]
![capture](https://cloud.githubusercontent.com/assets/9752096/6136182/9700d852-b13c-11e4-8502-2bb4b69ce9dc.PNG)
![capture 1](https://cloud.githubusercontent.com/assets/9752096/6136190/ae0cad8c-b13c-11e4-924f-4031deba30b9.PNG)

**Comment by lesgou** [comment]
Including updating the download file name that is consistent with the table, instead of the default "download.csv".

**Comment by awolfe76** [comment]
Fixed in f0b2ebf63de7d7fcd3ac2fa6a0f270c16844ecc6 

There isn't a consistent way to name the download file.
