### ISSUE TITLE
Passing the table to the controller

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-viz-prototype#59]
Create a table for Mike that pass the table to the controller (MSA list).

**Comment by awolfe76** [comment]
@Kibrael - we talked about doing this later (I think) but you should do it now. Just for now the only thing in the `.csv` will be the rows required to generate `/aggregate/2012/MSA`.

Make sense?

**Comment by Kibrael** [comment]
@awolfe76 Yep. I will work the file structure out soon. I think I'll get this part done close to the end of my milestone checklist.

**Comment by awolfe76** [comment]
:+1:

**Comment by Kibrael** [comment]
Should there be a file for each year?

Or should one file incorporate multiple years?

See MSAinputs in the processing folder for my current layout.

**Comment by awolfe76** [comment]
I think one csv per year ... for now. If the formats are the same though it would be easy to merge them together and pass that file in too.

I took a look at your file and I'm not quite sure I follow how that would work.
Totally up to you (whatever is easiest) I was thinking the csv might be something like:

`report-type, year, msa-id, report-id`

Where report type is aggregate or disclosure. So it's a pretty simple format but would get us everything we need ... I think. The csv would be long, many rows (number of msas x number of reports). But i think that's ok.

Other ideas? Maybe walk me through what you were thinking.

**Comment by Kibrael** [comment]
The reason I broke the disclosure reports out was that they would have list inputs for the report types. 

I think your ideas might make some other parts easier. I will think about it and see what i can come up with.

**Comment by Kibrael** [comment]
This is currently working, but may need future adjustments for disclosure reports.

I'm going to close it for now and we can make a new issue if we decide the way it works needs to change.
