### ISSUE TITLE
Merge the file into the jekyll structure

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-viz-prototype#60]

**Comment by awolfe76** [comment]
We've done this successfully. But I'm going to leave it open because very soon we'll need to start hosting the json files in another location, outside of the Jekyll structure.

For now we're in good shape.

**Comment by awolfe76** [comment]
Ok, going to close this now and when the time comes we'll create a new issue on how to setup the new structure.

Right now David creates a lot the directory structure for the reports, this includes `.json` files and `.md` files for Jekyll.
