### ISSUE TITLE
MSAs with no LAR entries

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-viz-prototype#71]
Do we need to create empty objects with headers?

@awolfe76

**Comment by awolfe76** [comment]
Hmm, do we have that case currently (on the current site)?
Can someone go down a path and see an empty table?

**Comment by lesgou** [comment]
No, if there is data, then there is a table.  If there is no data, there is no table.  There are some situations in which there are very few data points, so most of the table is blank.  But, it is not a completely empty table.

**Comment by awolfe76** [comment]
So, just want to make sure I have this right.

It is possible that an MSA doesn't have a table 3-1?

**Comment by lesgou** [comment]
Correct.  It is possible that when you pull up an MSA, that it doesn't have table 3-1 listed as an available table for the user to pull up.

**Comment by awolfe76** [comment]
Do they currently give that option at the end then? I walk through pick a state, pick a msa, then do I see 3-1 as an option? And if I do what's the table look like?

**Comment by lesgou** [comment]
3-1 may be a bad example, because all MSA's should have it.  but, as a user, if I were to pick a state, msa, and then I will see a list of all available reports for that only that msa.  the list of reports that display for each msa differs based on the submitted data.

**Comment by awolfe76** [comment]
Interesting. 
So I think this changes things a little. Right now in the UI I've basically hard coded the tables, the list of tables is the same no matter the path take to get there.

I think we need to create a json file, or some other way, to help the UI a bit.

Give the URL pattern of `/aggregate/2013/alabama/anniston-oxford/` we'll need a file in the `/anniston-oxford` directory that tells us what reports are available.

We do something similar to get the msa list. In `/alabama` there is a `msa-mds.json` file with the list of MSAs in that state. It looks like this:

``` json
{
    "msa-mds": [
        {
            "id": "11500",
            "name": "ANNISTON-OXFORD"
        },
        {
            "id": "12220",
            "name": "AUBURN-OPELIKA"
        },
        {
            "id": "13820",
            "name": "BIRMINGHAM-HOOVER"
        },
        {
            "id": "17980",
            "name": "COLUMBUS"
        },
        {
            "id": "19460",
            "name": "DECATUR"
        },
        {
            "id": "20020",
            "name": "DOTHAN"
        },
        {
            "id": "22520",
            "name": "FLORENCE-MUSCLE SHOALS"
        },
        {
            "id": "23460",
            "name": "GADSDEN"
        },
        {
            "id": "26620",
            "name": "HUNTSVILLE"
        },
        {
            "id": "33660",
            "name": "MOBILE"
        },
        {
            "id": "33860",
            "name": "MONTGOMERY"
        },
        {
            "id": "46220",
            "name": "TUSCALOOSA"
        }
    ]
}
```

Make sense?

**Comment by awolfe76** [comment]
@lesgou do you have an example path to see that happen?

**Comment by lesgou** [comment]
10380 - AGUADILLA-ISABELA-SAN SEBASTIAN, PR (2013)

Missing 4-5, 7-5, 8-3, 8-4, 8-5, 8-7, 11-4, 12-1, 12-2, A3

**Comment by awolfe76** [comment]
Cool. Thanks!

We'll need to output another json file in that case ... or we can show them all and just have those reports say something like "sorry no data here" (but a little more formal).

Ideas?

**Comment by Kibrael** [comment]
Is this the same as issue #85? If not, I'm not sure what to do here.

Can someone provide clarification on what they would like me to do?

**Comment by awolfe76** [comment]
Yeah, this is the same as #85, so I closed that one.

In the `msa-mds.json` files we need the list of MSAs that have reports, not the complete list of MSAs.
The format will still be the same as it is above, with the id and name.
