### ISSUE TITLE
Extracting table to csv

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-viz-prototype#73]
In Chrome and Firefox, when I extract the table to csv, I have to open excel, then open the downloaded file, then I am directed through the text form wizard.  In IE, when I extract the table to csv, it opens directly in an excel file.  Is there a way for Chrome and Firefox to extract in the same way IE does?

**Comment by awolfe76** [comment]
@lesgou - you can try this again.
If it's ok we can close it.

**Comment by lesgou** [comment]
I tried it and it is the same as before. Should we have someone else try it? Maybe it's just me.

**Comment by awolfe76** [comment]
Just want make sure where you are trying.
Is it here - http://awolfe76.github.io/hmda-viz-prototype/aggregate/2012/alabama/anniston-oxford/3-1/ in the awolfe76 version?

**Comment by lesgou** [comment]
Yes, just checked again.  Same result.

**Comment by awolfe76** [comment]
Ok. Thanks for checking. Going to work on something else for a bit and come back to this one.

**Comment by lesgou** [comment]
So it looks like this is just my pc.  Tried this on David's mac and pc, and csv's were extracted fine.

**Comment by awolfe76** [comment]
Cool. Closing out then.
