### ISSUE TITLE
Recommended enhancements for table format

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-viz-prototype#74]
- [x] Update the title of table to: Aggregate Table 3-1: Loans sold, by characteristics of borrower and of census tract in which property is located and by type of purchaser (includes originations and purchased loans), 2012.  Currently is: (a)ggregate Table 3-1: Loans sold(.) (B)y characteristics of borrower and census tract in which property is located and by type of purchaser (includes originations and purchased loans)(.), 2012 (goul'd)
- [x] When I print the table, there is a header that says "HMDA Viz Prototype", what will this be on a non hmda viz prototype site?
- [x] Consolidate Not Provided and Not Applicable under Race and Ethnicity under "Not Available" (goul'd)
- [x] Remove no co-applicant (goul'd)
- [x] Under Race, update "Native Hawaiian or Pacific Islander" to "Native Hawaiian or Other Pacific Islander" (goul'd)
- [x] Under Race, update "Joint" to "Joint (White/Minority Race) (goul'd)
- [x] Under Ethnicity, add "Joint (Hispanic or Latino/Not Hispanic or Latino) (goul'd)
- [x] For tables that go onto a second page, add a header on the top of the second page
- [x] Same updates for the extract to excel (except adding a header when the table goes to the second page.  That is not needed in excel)

**Comment by Kibrael** [comment]
- [x] fix ethnicitie and minority statuse in JSON object construction

**Comment by awolfe76** [comment]
@lesgou are those all in the UI? Do you know if they will require David to do anything? Except for the one he just added.

**Comment by lesgou** [comment]
They will, for example, the no co-applicant one.  He and I will discuss

**Comment by Kibrael** [comment]
I know some will require me to do some reworking.  Removing no co-applicant, adding Joint(Hispanic or Latino/Not Hispanic or Latino), consolidating Not Provided and Not Applicable under Race and Ethnicity.

I'm not sure what else, but the table name can be tweaked on my end.

**Comment by awolfe76** [comment]
Cool, thanks!

**Comment by Kibrael** [comment]
@awolfe76 I'll send you a new set of files today (they're running now), let me know if you need edits on my side.

**Comment by awolfe76** [comment]
For "When I print the table, there is a header that says "HMDA Viz Prototype", what will this be on a non hmda viz prototype site?"
That can be whatever we need it to be, it's easy to change. When printing you can also remove the header and footer in the print screens.

For "For tables that go onto a second page, add a header on the top of the second page"
Do you mean on the print? That seems to be something each browser handles differently. FF seems pretty smart about it, other browsers not so much.

For "Add a "Report Date" to show when the report is as of"
Should that be the date the json files are created? Or some other past date?

**Comment by lesgou** [comment]
For the first comment, that's cool
For the second comment, yes on the print.
For the third comment, yes, it is the date the json files are created.  I think this is so users know when the reports were run.

**Comment by Kibrael** [comment]
In regard to comment 3, I think referencing the version of HMDA that the reports were run on would be important. I think the date that the aggregate reports are created is only important in so far as it links to the underlying data version.

**Comment by awolfe76** [comment]
For 3, I think we'll need to add that to the json objects, in the header data. Just something simple:
"date-created": date,

For 2, I've added something to try for IE. FF is good. Chrome doesn't work though - https://code.google.com/p/chromium/issues/detail?id=24826

**Comment by lesgou** [comment]
I am wondering if we should add commas to the report.  It's not current state, but it makes sense, no?

**Comment by awolfe76** [comment]
Yeah, i think it makes sense for commas too. I created #78 as a place holder for it.

**Comment by lesgou** [comment]
I added "(goul'd)" after the ones that I have checked.

**Comment by Kibrael** [comment]
Do we want the 'As of Date' to be the date the data was processed? 
@awolfe76 do you want this in the header section?

**Comment by awolfe76** [comment]
Yeah, in the header section.
On ffiec they have 'Report Date: xx/xx/xxxx'. We can call it whatever in the json but 'report-date': xx/xx/xxxx works. I'll output the text correctly on the front-end.

**Comment by awolfe76** [comment]
@lesgou @Kibrael either of you object to me pulling #'s 2, 3, and 5 into their own issue?
I think it may be justified, they may have more work around them.

**Comment by Kibrael** [comment]
Fine by me.

**Comment by awolfe76** [comment]
Cool. Closing now. Opened #91, #92, #93.
