### ISSUE TITLE
generate a list of reports that were run for each msa

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-viz-prototype#77]
track the reports that were generated and save in the MSA directory

@awolfe76 what file structure is best for you?

**Comment by Kibrael** [comment]
Does this structure work:

{
    "id": "17980", 
    "name": "columbus", 
    "reports": [
        "4-2", 
        "4-4", 
        "4-6", 
        "5-2", 
        "5-4", 
        "7-2", 
        "7-4", 
        "7-6"
    ]
}

**Comment by awolfe76** [comment]
The files will be in the `type/year/state/msa-md/` directory, eg Anniston-Oxford reports would be listed here `/aggregate/2013/alabama/anniston-oxford/` in a `reports.json` file.

Because of that we won't need the `id` and `name`. Something like the [msa-mds.json](https://github.com/cfpb/hmda-viz-prototype/blob/gh-pages/aggregate/2013/alabama/msa-mds.json) will work fine.

Example:

```
{
    "reports": [
        {
            "id": "4-2",
            "name": "Conventional Purchases By Race"
        }, 
        ...
    ]
}
```

**Comment by Kibrael** [comment]
Thanks Andrew, I'll work that up.

**Comment by Kibrael** [comment]
Approve or deny?

{
    "reports": [
        {
            "id": "4-2", 
            "name": "Disposition of applications for conventional home-purchase loans 1- to 4- family and manufactured home dwellings, by race, ethnicity, gender and income of applicant"
        }, 
        {
            "id": "4-4", 
            "name": "Disposition of applications for home improvement loans, 1- to 4- family and manufactured home dwellings, by race, ethnicity, gender and income of applicant"
        }, 
        {
            "id": "4-6", 
            "name": "Disposition of applications from nonoccupants for home-purchase, home improvement, or refinancing loans, 1- to 4- family and manufactured home dwellings, by race, ethnicity, gender and income of applicant"
        }, 
        {
            "id": "5-2", 
            "name": "Disposition of applications for conventional home-purchase loans, 1- to 4-family and manufactured home dwellings, by income race, and ethnicity of applicant"
        }, 
        {
            "id": "5-4", 
            "name": "Disposition of applications for home improvement loans, 1- to 4-family and manufactured home dwellings, by income, race and ethnicity of applicant"
        }, 
        {
            "id": "7-2", 
            "name": "Disposition of applications for conventional home-purchase loans, 1- to 4-family and manufactured home dwellings, by characteristics of census tract in which property is located"
        }, 
        {
            "id": "7-4", 
            "name": "Disposition of applications for home improvement loans, 1- to 4-family and manufactured home dwellings, by characteristics of census tract in which property is located"
        }, 
        {
            "id": "7-6", 
            "name": "Disposition of applications from nonoccupatns for home-purchase, home improvement, or refinancing loans, 1- to 4-family and manufactured home dwellings, by characteristics of census tract in which property is located"
        }
    ]
}

**Comment by awolfe76** [comment]
:+1:
