### ISSUE TITLE
List of tables for MSA page not found

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-viz-prototype#85]
I selected 2012, Alaska, and Ketchikan, and got a page not found;

http://awolfe76.github.io/hmda-viz-prototype/aggregate/2012/alaska/ketchikan/

http://awolfe76.github.io/hmda-viz-prototype/aggregate/2012/california/ukiah/

![image](https://cloud.githubusercontent.com/assets/9752096/6468783/84e372aa-c1a5-11e4-96e5-caf610a0d98e.png)

**Comment by awolfe76** [comment]
Yeah, i've noticed some of this too. There are msa/mds listed in the json files (the `msa-mds.json` files) that don't have a directory created.

**Comment by Kibrael** [comment]
Were these files only supposed to have MSAs which had reports generated?

**Comment by awolfe76** [comment]
Yeah, I think so.

That's what I'm using to build the UI, the select options come from there. Sorry if I didn't explain that well.

**Comment by Kibrael** [comment]
Ah, ok, I understand now. I misunderstood.

@awolfe76 : was there another output you wanted that tracked all MSAs in a state?

**Comment by awolfe76** [comment]
No, I don't think so. Just wanted all MSAs that have reports.
Thanks!

**Comment by awolfe76** [comment]
See #71
