### ISSUE TITLE
3-2 json

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-viz-prototype#86]
- [x] `first lien count` should be `firstliencount` without spaces
- [x] same for the other keys (first and junior / counts and values)
- [x] the `median` and `means` should have both counts and values too 
- [x] the numbers seem off on the `median` and `mean` too (compared to current ffiec)

**Comment by Kibrael** [comment]
For the mean and medians: did you want counts and values end points in the JSON object? I don't see them on the report. I am also confused as to how there are different values for those fields between report pages.

**Comment by awolfe76** [comment]
On FFIEC go to 2012, Alabama, Anniston-Oxford, 3-2.
On there they show mean and median values.
The values for the #'s and very close to the numbers in the 000's but not always the same. Might be that they are doing the math a bit differently each time? I have no idea.

@lesgou, any ideas?

**Comment by Kibrael** [comment]
We are thinking that one is using dollar weighted on one and simple mean/median on the other.

If they're calculated differently, then I'll need some time to add an extra piece of code.

**Comment by lesgou** [comment]
So, for the mean/median on the first page, there are no footnotes.  On the second page, there are footnotes 30 and 31:
1. for each loan category, the dollar weighted mean spread is calculated by multiplying each loan with a reported price spread times the dollar amount of the loan and dividing the sum of these dollar weighted loan prices by the total dollar amount of loans in the product category.
2. for each loan category, the dollar weighted median spread is calculated for each loan with a reported price spread by weighting each loan as represented by its rate spread using the dollar size of the loan amount. then find the rate spread of the loan at the midpoint of this distribution of loan dollars.

I need to follow up on 31, and see if we can find an explanation for that.

**Comment by awolfe76** [comment]
Should we just try what you are thinking?

**Comment by Kibrael** [comment]
Do the means and medians need counts and values for consistency in outputting? I don't see them as actually having counts (in concept).

**Comment by awolfe76** [comment]
Yeah, definitely just for consistency.

**Comment by awolfe76** [comment]
Closing this. See #90
