### ISSUE TITLE
Add the footnotes (i.e., 5/).  Or should we go with another format?  5*?

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-viz-prototype#92]
We should talk about how to implement this. My first take is that I should do it on the front-end.

The json files don't seem like a good place to keep this. 

Any other thoughts?

**Comment by lesgou** [comment]
Front end seems to make sense to me.  My other question is then do we want a separate page for footnotes?  Or, be really fancy and have a hyperlink?  Or a bubble that appears when people hover?  but considering how complicated some of these footnotes can be, the hovering bubble may not be helpful.

**Comment by awolfe76** [comment]
Yeah, I was thinking a combination of the first and second options. Just create a footnotes page and link to it.
Sounds like a winner.

**Comment by awolfe76** [comment]
@lesgou - are the footnotes broken down in anyway currently? Like aggregate footnotes and disclosure footnotes?
Thinking about where that page should live ... /footnotes or /aggregate/footnotes?
Or if they are different per year, /aggregate/2012/footnotes?

And any chance of getting them in a friendly format (assuming they are in a pdf now)?

**Comment by lesgou** [comment]
The footnotes are by year, not by reports.  I can get you the 2012 and 2013 footnotes. 
Does it make sense to do /footnotes/2012?

**Comment by awolfe76** [comment]
:+1:

**Comment by lesgou** [comment]
Right now they aren't in exactly the best format: http://www.ffiec.gov/hmdaadwebreport/footnote_HMDA2013.htm

Would you prefer that I put them into word (not all capitalized), or....what works best for you?

**Comment by awolfe76** [comment]
This works just like this. I can grab them from there.
Thanks!

Are you sure we don't want all caps? :wink:

**Comment by awolfe76** [comment]
I think we're good here.
