### ISSUE TITLE
Consistency with the format of the wording with regards to capital and lower case letters. 

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-viz-prototype#93]
@lesgou - did you mean in the report titles and descriptions?
Or other places too?

**Comment by lesgou** [comment]
in the table, but @Kibrael may have already fixed it for table 3-1.

Just consistency for the table (row and column) headers.  If we just have the first letter capitalized, then everything else lower case, that is fine.  but if every letter is capitalized, then it just has to be consistent throughout the table.

**Comment by awolfe76** [comment]
Ok, @Kibrael I did notice in 3-2 that the mean and median were lower case too.

**Comment by Kibrael** [comment]
I fixed this in the json constructor.

I ran updated reports for MSA 11500 (Anniston), I will send them to you both soon.
