### ISSUE TITLE
Table 3-2 N/A's for junior lien's

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-viz-prototype#94]
For Junior Lien, since below 3.5% does not apply, should there by N/A in those rows instead of zero?
![capture](https://cloud.githubusercontent.com/assets/9752096/6492646/2628d9ce-c283-11e4-8ee1-569513aca605.PNG)
?  This is how it is currently done:

**Comment by awolfe76** [comment]
@lesgou - i'm not sure if this is a front-end thing or something when @Kibrael is processing?
Is it 'if that value is <3.5 display NA'?

I see a lot of NA's in the screenshot, so just not sure what we're doing.

**Comment by Kibrael** [comment]
I can set the default for all those end points to NA if you want.

That would mean only the ones that had numbers calculated would have numbers to display.

**Comment by awolfe76** [comment]
Sounds good, is that pretty easy for you to do on your side?

**Comment by Kibrael** [comment]
Yeah, I think it'll take 3 lines of code and just a few minutes. It just means a condition and changing the 0 to NA.

**Comment by awolfe76** [comment]
Cool. Thanks @Kibrael !

**Comment by lesgou** [comment]
For reference purposes: See (e) below:

Per the Getting it Right Guide Page 41:
b. If the loan is not subject to Regulation Z, or is a home improvement loan that is not dwelling-secured, or is a loan that you purchased, enter “NA.”
c. Enter “NA” in the case of an application that does not result in a loan origination.
e. If the difference between the APR and the average prime offer rate is less than 1.5 percentage points for a first-lien loan and less than 3.5 percentage points for a subordinate-lien loan, enter “NA.”

Users enter N/A, so 0 would be inaccurate.

**Comment by Kibrael** [comment]
I changed the first 4 categories of Junior Lien to 'NA' and the rest of the categories to 0.

Let me know if this doesn't work. I was going off the Anniston report on the FFIEC site, and the cells are blank for no data cells.
