### ISSUE TITLE
Adding a space in the header for table 4-1

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-viz-prototype#95]
Can a space be added after the "4-"? This will make it consistent with the "1-"

Aggregate Table 4-1: Disposition of applications for FHA, FSA/RHS, and VA home-purchase loans, 1- to 4-family and manufactured home dwellings, by race, ethnicity, gender and income of applicant, 2012

**Comment by Kibrael** [comment]
Sure, I was just copying FFIEC language.

Do you want that for all the 4 series?

**Comment by Kibrael** [comment]
Added to all table descriptions.
