### ISSUE TITLE
Tables 4-1 and 4-2 Aesthetics

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-viz-prototype#96]
- [x] 1. The last category, "Income of the Applicants", "income not available", the "i" should be capitalized.
- [x] 2. The headers under "Race and Gender" are bolded and have "(Total)" after the header. This should be consistent for the headers in the "Ethnicity, Gender, and Income" table.
- [x] 3. Recommend adding commas 
- [x] 4. The table header name for 4-2 is missing

**Comment by Kibrael** [comment]
@awolfe76 can you tell me if any of these are on my end?

**Comment by awolfe76** [comment]
@Kibrael i think the table header one is, number 4.
See this screenshot:
![no-header](https://cloud.githubusercontent.com/assets/2932572/6493843/8315b140-c28b-11e4-933d-757188a4f051.png)
That's because the json in 4-2 has this:

```
"table": "4-2", 
"type": "Aggregate", 
"desc": null, 
"year": "2012", 
```

The `desc` is `null`

The rest are me.

**Comment by Kibrael** [comment]
Roger, thanks Andrew. I have added descriptions for all tables through 4-7.

**Comment by awolfe76** [comment]
:boom:
