### ISSUE TITLE
Differences in 2012 and 2013 reports

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-viz-prototype#97]
In the 4's for 2012 it has the correct (plural to singular)

```
"incomes": [
        {
            "income":
```

but 2013 still shows

```
"incomes": [
        {
            "incomes":
```

2012 has the new `"report-date"`, 2013 doesn't.

And I just happened to notice that in the 2013's report 4-3 didn't get created.

**Comment by Kibrael** [comment]
I believe all these are done, so I'm closing it. Let me know if it needs to be re-opened.
