### ISSUE TITLE
Timing of report creation

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-viz-prototype#98]
Setup a way to tell the time it takes to generate the reports. May need to get detailed:
- for 3-1 in 2012 it took x minutes
- or for 3-1 in 2012 Alabama/Anniston took x minutes

We can work out what exactly we need later. 

@Kibrael - I don't think this is for this milestone, more like something we want in a while ... really similar to the logging ( #75 ). May even be part of that.

**Comment by Kibrael** [comment]
The individual reports are typically less than a minute (after applying an MSA index to the SQL table). Do you think it's worthwhile to know report creation in seconds?

**Comment by awolfe76** [comment]
No, a bad example. :smile: 
We wouldn't need to time one specific report. But a whole year or all of 3-1. 
A lot of the depends on the order you are generating them too.

**Comment by Kibrael** [comment]
Ok, thanks. I'll get it to start time stamping.
